### ISSUE TITLE
ERROR: https://www.soliscloud.com:13333/v1/api/inveterList -> 502: Bad Gateway

### ISSUE THREAD

**Issue by silviudc** [ZuinigeRijder/SolisCloud2PVOutput#11]
Getting this error when I tried the script out, I have a valid clientid and key but I see that the API doc is at 1.2 now, not sure if something needs to be updated in the python script?
Any ideas?
[SolisCloud API 1.2.pdf](https://github.com/ZuinigeRijder/SolisCloud2PVOutput/files/10094892/SolisCloud.API.1.2.pdf)

**Comment by ZuinigeRijder** [comment]
I also get sometimes in the error logging, examples of today:

20221125 05:02:23: ERROR: https://www.soliscloud.com:13333/v1/api/inveterList ->                                                                                            502: Bad Gateway
 
20221125 22:01:26: ERROR: https://www.soliscloud.com:13333/v1/api/inveterDetail                                                                                            -> 502: Bad Gateway

However, after some retries it works. So it is about the SolisCloud server, which is sometimes not reachable, so expect something at the SolisCloud site.

I also see that in V1.2 the method names (typos) are corrected into:
http://www.soliscloud.com:13333/v1/api/inverterList
http://www.soliscloud.com:13333/v1/api/inverterDetail

But the names with typos are still supported!
I know this, because my scripts are still running ok on my Raspberry Pi with the old method names....... 

So I expect this is just a problem server side of SolisCloud, not always reachable......

**Comment by silviudc** [comment]
Yes must have been bad timing when I tried.
Works ok now, thanks.
