### ISSUE TITLE
Power Used always at 250W

### ISSUE THREAD

**Issue by ajmmw** [ZuinigeRijder/SolisCloud2PVOutput#15]
Not sure if this by design however the Power Used is always displaying at 250W is there a way to show what my actual power used each time?

**Comment by ZuinigeRijder** [comment]
I misuse this "Power Used" PVOutput field for showing the AC voltage. So it is not Watt, but Voltage. The AC Voltage is important, because when it is too high, the Solis converter will switch off (At least in the Netherlands, I believe around the 254 Volt). If that is the same for you, than you are close with 250 Volt to the limit before the Solis converter switches off. But maybe for your region settings, this is different.

I tried to explain in the [README](https://github.com/ZuinigeRijder/SolisCloud2PVOutput#soliscloud-to-pvoutput):

- AC voltage (max voltage of 3 phases, used "Power Consumption" field, so read "AC Volt" for the "Power Used" column of PVOutput and ignore "Energy Used" column)

**Comment by pnkllr** [comment]
Ah thats the same for us here to in Aus.

Is there a build where I can display the actual power consumed tho? Rather than the voltage? Me and a friend like to compare our solar each day but its saying my usage is really low each day.

Im happy to edit the cfg file with the needed fixes, I just dont know the actual output of the API data.

**Comment by ZuinigeRijder** [comment]
The Solis inverter does not have information about your "Power Used" AFAIK. Or do you have also battery storage attached and you have a Solis Hybrid Inverter? Anyway, currently there is no option in the script for getting "Power Used".

**Comment by pnkllr** [comment]
![image](https://user-images.githubusercontent.com/915212/230379334-ed8ae427-0e18-444f-a720-feff1098c97d.png)
![image](https://user-images.githubusercontent.com/915212/230379400-6ec04815-4733-4c96-bda5-dbdc2f45d56b.png)

**Comment by ZuinigeRijder** [comment]
Ah, thanks. I do not have a Solis Consumption Monitoring Solution, only a Solis Inverter.
Your solution [is mentioned here](https://www.ginlong.com/us/documentation/36055.html), I think.

> Solis offers 2 types of single-phase smart meters and 2 types of three-phase smart meter with different connections: Direct Insert Type or External CT Type.

I do not have this, so I can also not try it out. In the [Solis API documen](https://github.com/ZuinigeRijder/SolisCloud2PVOutput/blob/main/2022.5.3SolisCloudMonitoringAPI1.1.1.pdf)t I see something like this in /v1/api/inveterDetail
(Inverter Details):
> gridPurchasedToday Energy
> gridSellToday Energy

So probably "Power Used" can be computed with this. But as said, I do not have this monitor solution, so difficult to provide/change the SolisCloud2PVOutput script.

**Comment by pnkllr** [comment]
Testing the following 
`timestamp_current = inverter_detail['dataTimestamp']
        familyLoad = round(inverter_detail['familyLoadPower'] * 1000) # Grab Power Used in W (is it just from grid or all together, check when panels generate power)
        volt = (
            inverter_detail['uPv1'] +
            inverter_detail['uPv2'] +
            inverter_detail['uPv3'] +
            inverter_detail['uPv4']
        )`

and sending it to ouput

`pvoutput_string = (
                'data=' + TODAY +  # Date
                ',' + datetime_current.strftime("%H:%M") +  # Time
                ',' + str(hi_res_watthour_today) +  # Energy Generation
                ',' + str(watt) +  # Power Generation
                ',-1' +  # no Energy Consumption
                ',' + str(familyLoad) +  # Power Consumed in W
                ',' + str(inverter_temp) +  # inverter temp iso outside temp
                ',' + str(volt)  # Voltage
            )`

Will need to test to see if this power is just consumed via the grid or contains both from panels and grid when panels generate power

**Comment by ZuinigeRijder** [comment]
@pnkllr   And what did the test reveal?

**Comment by pnkllr** [comment]
Sorry forgot to update! 

Seems it's now reporting the correct consumption of power!

![image](https://user-images.githubusercontent.com/915212/235354297-844ca9ca-8c4c-405f-9728-04cf181feb92.png)

**Comment by cajsoft** [comment]
I think this also will fix my issue getting power used from hybrid solis inverter :)

**Comment by ZuinigeRijder** [comment]
@pnkllr I am a bit confused, because someone with a hybrid solis inverter with battery is using psum. See this discussion:

https://github.com/ZuinigeRijder/SolisCloud2PVOutput/discussions/24

You are using familiyLoadPower?
What is psum giving for you? 
What is the difference with psum?
And the addition of pac, psum and batteryPower?

Maybe I can incorporate/support with a configuration setting both situations.

**Comment by pnkllr** [comment]
Familyload is all power consumed from all sources

**Comment by ZuinigeRijder** [comment]
And what is psum giving you?

````
psum = round(inverter_detail['psum'] * 1000) 
````

Can you post a screenshot with your system, like in this post:
https://github.com/ZuinigeRijder/SolisCloud2PVOutput/issues/15#issuecomment-1498992646

And then give the values of familyLoadPower, psum and watt?
That would give me better insight.

**Comment by quimnut** [comment]
There's a voltage field in PVOutput so why put it in power used?

**Comment by ZuinigeRijder** [comment]
> There's a voltage field in PVOutput so why put it in power used?

I do not have a Solis consumption monitor solution and AC voltage is important, if it is too high the inverter will stop. So I want to keep track of AC voltage too and no standard PVOutput field is available for this (Voltage is used for DC voltage).

See this post: https://github.com/ZuinigeRijder/SolisCloud2PVOutput/issues/15#issuecomment-1498940684

**Comment by JeroenEeuwes** [comment]
> I do not have a Solis consumption monitor solution and AC voltage is important, if it is too high the inverter will stop. So I want to keep track of AC voltage too and no standard PVOutput field is available for this (Voltage is used for DC voltage).

I just modified my local version to send the value of AC volt to PV Output. I don't really care about the DC volt value.

I don't think PV output specifies that is has to be DC volt, just like it doesn't specify what the temperature field is for. Some people put in their inverter internal temperature others the weather temperature (and there are probably other values too).

@quimnut perhaps you can change it to send AC Volt that in your local copy, too.

**Comment by ZuinigeRijder** [comment]
@pnkllr [the new version](https://github.com/ZuinigeRijder/SolisCloud2PVOutput/releases/tag/R1.13.0) should now support your use case using configuration. Maybe you can test if this is working for you? Especially because I do not have a solis monitoring solution installation.

**Comment by ZuinigeRijder** [comment]
Closed.
