### ISSUE TITLE
Cron task has stopped existing tasks running

### ISSUE THREAD

**Issue by telemarker73** [ZuinigeRijder/SolisCloud2PVOutput#26]
Hi - I set this python script up on my freenas Linux install, it runs OK thanks
But the cron job stops all the existing cron jobs running on my system now as soon as it runs they stop :(
I setup cron using the web UI interface on freenas

I also since modified the cron command and still have the issue of other tasks not running once the soliscloud2pvoutput one runs.

![D7972053-FEFE-4DD6-8014-276ED0473682](https://github.com/ZuinigeRijder/SolisCloud2PVOutput/assets/137273211/c1837264-4167-46fc-a3b9-353760bbf82c)

**Comment by ZuinigeRijder** [comment]
Very strange. Probably it has to do with your freenas Linux install. The soliscloud_to_pvoutput.py script does work and then sleeps 60 seconds in a loop. Apparently your freenas Linux install does not run other cron tasks when that one is not ended?

Questions: 
1. What happens when you run the solis.sh from the command line? Are the other cron jobs then also stopping?
2. What happens when you run the Command in the background, by adding an & at the end

````
/bin/sh -x /root/solis/solis.sh &
````

Note that you should not need to run solis.sh as root.

**Comment by telemarker73** [comment]
Thanks for fast reply
When I run solis.sh from command line the other cron tasks run ok
And if I kick the solis.sh from cron UI manually it runs and other tasks also continue to run
It’s only when cron task for solis.sh runs at 5am then all the other tasks fail to run after 5am until I reboot NAS.

I will try option 2 you suggest
And also add cron task via cron tab -e instead 

last resort I will reinstate my raspberry pi and set the script up on that

**Comment by telemarker73** [comment]
Hi 
This didn’t fix it either
I will try in raspberry pi instead

**Comment by ZuinigeRijder** [comment]
Closed.
