### ISSUE TITLE
Not python3 compatible

### ISSUE THREAD

**Issue by kverkind** [ZuinigeRijder/SolisCloud2PVOutput#32]
hmac_obj = hmac.new(
            SOLISCLOUD_API_SECRET,
            msg=encrypt_str.encode("utf-8"),
            digestmod=hashlib.sha1,
        )
trows error

**Comment by ZuinigeRijder** [comment]
Can you post the error? 
What version of python3 are you using?
What operating system are you using?

**Comment by kverkind** [comment]
Python 3.7.3
OS is Raspbian 10 (buster)
Error is:
 raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str


If I  change the code as below, then it passes but I get "403 Forbidden"
hmac_obj = hmac.new(
SOLISCLOUD_API_SECRET.encode("utf-8"),
msg=encrypt_str.encode("utf-8"),
digestmod=hashlib.sha1,
)

**Comment by ZuinigeRijder** [comment]
Ah, ok. You need to install Python 3.9 or higher. I have installed Python 3.9.2 on my Raspberry Pi with Raspbian GNU/Linux 11 (bullseye). I do not know if you can upgrade the python version to 3.9 or higher on Buster.  Otherwise you need to upgrade to BullsEye. I need to add the needed Python to the README, I guess.

**Comment by kverkind** [comment]
Please ignore. The encode statement is there already when reading the value. I did put a "/" after the url port number in the config file resulting in a "//".
